alias rm='rm --interactive=always '
alias xopen='xdg-open '
alias mc='mc --skin="/usr/share/mc/skins/xoria256.ini" '
alias myip='wget -qO- http://ipecho.net/plain ; echo' 
alias wgetdir='wget --no-parent --wait=10 --random-wait -e robots=off --mirror --recursive --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"'
alias matlab='matlab -nodesktop -nosplash '
